### PR TITLE
added lifetime_karma

### PR DESCRIPTION
**Pull request by SHARDcoder**
useless but idc

### CODE REVIEW

**Comment by ConorTheDev** [comment]
I'm confused, what does this do?

**Comment by SHARDcoder** [comment]
im trying to add a karma counter but am nub
lemme finish committing things plz

**Comment by ConorTheDev** [comment]
Would you not just add it all in one commit? Why is it a settings option?

**Comment by SHARDcoder** [comment]
am bad ok
also its not an option. its a counter
lemme do it in 1 commit

**Pull request closed without merging**
