### PR TITLE
Hyperium FPS Mode

### PR DESCRIPTION
**Pull request by RDIL**
## Description  
  
plz no bully me   
I'm fine with constructive feedback but please avoid being rude 
## Context  
  
koding was going to do this but umm here we are
## Anything Else  

cc @CoalCoding 
## Checklist  

- [X] All *new* Java and Kotlin files have the right copyright header  
- [X] I have tested my code by building it locally  
- [X] This is not a work-in-progress and is ready for merge  
- [X] I am submitting the PR under and understand the terms of the GNU Lesser General Public License v3.0

### CODE REVIEW

**Comment by asbyth** [comment]
1: you could've just put this with the other pr
2: i dont think this would help framerate in the slightest, isnt everything still loaded into the memory? i could very well be wrong but it's like why replay would be put as an addon despite all of the requests, because even if you dont use it, it'd still hog up more ram, all of these features are still loaded into the client, disabling it doesnt make it think "oh ok i just wont load into the memory this time, enjoy your framerate"

**Comment by CoalCoding** [comment]
Personally I think a better way to achieve this would be to make the individual Hyperium settings fully enable/disable their relevant parts as you have done. And then make "FPS Mode" simply be a pre-defined list of settings with all the unnecessary things disabled. This could be in a separate button near the top of the settings menu and we can potentially have more presets in the future.

**Comment by RDIL** [comment]
True.  Not a bad idea.

**Comment by RDIL** [comment]
Not sure exactly how I could do your idea coal as intellij won't let me modify values of settings from the main class as they are static.

**Comment by RDIL** [comment]
I guess since you both think this is a bad approach
ill reopen if you want me to

**Pull request closed without merging**
