### PR TITLE
change panorama from china new year hub to normal hub

### PR DESCRIPTION
**Pull request by MODKILLER1001**

### CODE REVIEW

**Comment by MODKILLER1001** [comment]
all are correct

**Comment by 9Y0** [comment]
All files ends with .png.png That's what boom is referring to

**Comment by MODKILLER1001** [comment]
old files were named same way

**Comment by 9Y0** [comment]
how is `panorama0.png` the same as `panorama_0.png.png`?

**Comment by MODKILLER1001** [comment]
will fix

**Pull request closed without merging**
