### PR TITLE
JsonHolder optimization and documentation

### PR DESCRIPTION
**Pull request by ReflxctionDev**
## Description  
This optimizes the heavily-used JsonHolder:
* You create a **new** JsonParser **every time** you create a JsonHolder. I don't think I need to explain how inefficient this is, right? It will now use Gson to deserialize it as a JsonElement. After a couple of microbenchmarks and continuous testing, this was much faster than using a JsonParser.
* Documented the entire class and documented every method, as well as organizing methods' positions 
* Changed **#getJsonArrayAsStringList(String)** to be more efficient. It used to loop through the entire array and add elements manually. It will now just deserialize the JsonArray into a **LinkedList<String>**.
* Removed @SuppressWarnings("unused"). If you want to optimize your client remove unused methods lol
  

## Checklist  

- [x] All *new* Java and Kotlin files have the right copyright header  
- [x] I have tested my code by building it locally  
- [x] This is not a work-in-progress and is ready for merge  
- [x] I am submitting the PR under and understand the terms of the GNU Lesser General Public License v3.0

P.S: The actual commit that contains **the majority of changes** is the [first commit](https://github.com/HyperiumClient/Hyperium/pull/630/commits/ca1d3c45e74a898581927d13a72dbbbf329c2ff2). The [second commit](https://github.com/HyperiumClient/Hyperium/pull/630/commits/56b37b6d67b712a0d6064b1808e0188d44aa337d) fixes an issue in building it. (idk why, probably the error existed when I cloned)

### CODE REVIEW

**Comment by ReflxctionDev** [comment]
> Can you replace a few existing uses of the old method? Just think it would be better if the class was actually used for the time being.

The entire Hyperium code was using **cc.hyperium.utils.JsonHolder** from the [Installer repository](https://github.com/HyperiumClient/Installer/blob/master/src/main/java/cc/hyperium/installer/utils/JsonHolder.java). By me adding it to the actual code (not using an external library), it will use the one I added automatically and override it on the one from the installer repo

**Comment by ReflxctionDev** [comment]
P.S: The actual commit that contains **the majority of changes** is the [first commit](https://github.com/HyperiumClient/Hyperium/pull/630/commits/ca1d3c45e74a898581927d13a72dbbbf329c2ff2). The [second commit](https://github.com/HyperiumClient/Hyperium/pull/630/commits/56b37b6d67b712a0d6064b1808e0188d44aa337d) fixes an issue in building it. (idk why, probably the error existed when I cloned)

**Comment by asbyth** [comment]
all hail the documentation god for making code readable and pretty to dumbasses like me

**Comment by RDIL** [comment]
Don’t use a negative mindset asbyth, stay positive.

**Pull request merged**
