### PR TITLE
Removed unused resource(s) related to mcef

### PR DESCRIPTION
**Pull request by Cubxity**
## Description  
  
Removed unused resource(s) related to mcef

## Context  
  
Nothing special

## Checklist  

- [x] All *new* Java and Kotlin files have the right copyright header  
- [x] I have tested my code by building it locally  
- [x] This is not a work-in-progress and is ready for merge  
- [x] I am submitting the PR under and understand the terms of the GNU Lesser General Public License v3.0

### CODE REVIEW

**Comment by Cubxity** [comment]
Nevermind, i forgot to update my repo

**Comment by asbyth** [comment]
you are Stupid

**Comment by KodingKing1** [comment]
you are haves stupid

**Comment by KodingKing1** [comment]
fullstop.

**Comment by GamingGeek** [comment]
l m a o

**Pull request closed without merging**
