### PR TITLE
Fixed progress bar. Now disappears on successful load.

### PR DESCRIPTION
**Pull request by KodingKing1**
Fixed progress bar. Now disappears on successful load.

Changed loading screen to look like below:
screenshot_33

### CODE REVIEW

**Comment by RDIL** [comment]
Won’t adding a progress bar slow it down at least a little?

**Comment by KodingKing1** [comment]
It only draws the bar when the variable gets updated. Ie, 12 times each startup.

**Comment by RDIL** [comment]
Ah ok

**Comment by KodingKing1** [comment]
Should be fixed now.

**Pull request merged**
