### PR TITLE
Added The Pit and SkyBlock, also removed SkyClash

### PR DESCRIPTION
**Pull request by Noctember**
Pull templates?
**Huh?**

_Don't forget to add new icons for The Pit and SkyBlock_

### CODE REVIEW

**Comment by GamingGeek** [comment]
The names should match what is listed [here](https://github.com/HypixelDev/PublicAPI/blob/master/Documentation/misc/GameType.md), for example `TNT Games` instead of `The TNT Games`

**Comment by asbyth** [comment]
whats up with the formatting on the first one?

**Comment by Noctember** [comment]
Thats github not adding the line since I edited the file from my browser

**Comment by asbyth** [comment]
i'll add it in the other branch (mcgradle)

**Comment by asbyth** [comment]
actually this isnt inline with their document, and whats up with the ids?

**Comment by asbyth** [comment]
> actually this isnt inline with their document, and whats up with the ids?

realizing now, id's are meant to be added into the discord rpc as it corresponds with the image displayed on rpc

**Pull request closed without merging**
