### PR TITLE
Add some events (I hope it's work)

### PR DESCRIPTION
**Pull request by SiroQ**
I cannot test my code because I don't know how to obfuscate Hyperium...

### CODE REVIEW

**Comment by ConorTheDev** [comment]
Just run `gradlew runClient` to test

**Comment by SiroQ** [comment]
I did, but my event test addon cannot start with this error...
https://pastebin.com/SY8d4F28

**Comment by SiroQ** [comment]
I tested it on my addon and It seem working.

**Comment by ConorTheDev** [comment]
Okay, I'll clone your fork later and see.

**Comment by SiroQ** [comment]
Added #345

**Pull request closed without merging**
