### PR TITLE
Added /levelhead toggle

### PR DESCRIPTION
**Pull request by SHARDcoder**
this should hopefully work
someone in the discord suggested it
bad code make it better i dont mind
thank you for your time

### CODE REVIEW

**Comment by Sk1er** [comment]
There already is a toggle tho. /levelhead and turn it off...

**Comment by Sk1er** [comment]
https://github.com/SHARDcoder/Hyperium/blob/21c2ff3831fb1d10d5996fa1529028ca1dc7c2e9/src/main/java/cc/hyperium/mods/levelhead/Levelhead.java#L120

https://github.com/SHARDcoder/Hyperium/blob/21c2ff3831fb1d10d5996fa1529028ca1dc7c2e9/src/main/java/cc/hyperium/mods/levelhead/guis/LevelHeadGui.java#L109

**Comment by SHARDcoder** [comment]
I'm aware, thanks
Should I go through and do this sort of thing for all the implemented mods in case people prefer commands than having to open a gui / mess with settings in /hyperiumconfig

**Comment by SHARDcoder** [comment]
Sorry for being a waste of time, I just wanna help in some way so I can appreciate how hard it was to make this all work and not crash on startup like most stuff I work on does

**Comment by SHARDcoder** [comment]
Thanks 👍 
I'm bad at code

**Comment by boomboompower** [comment]
Gonna change it to use normal levelhead config

**Comment by boomboompower** [comment]
Implemented it on https://github.com/HyperiumClient/Hyperium/commit/e3851433f01b5f59f995afc4dce9ba62ec677501

**Comment by SHARDcoder** [comment]
thanks

**Pull request closed without merging**
