### PR TITLE
Docs on readthedocs

### PR DESCRIPTION
**Pull request by RDIL**
What you have to do after merging my PR:
* Go to https://readthedocs.org/
* Sign in with Github
* Click on import a project
* Select this repo
* Fill your preferences
* Wait for the doc to build
* Enjoy your new doc!

***Important: if possible don't squash and merge this pull request it sometimes messes with readthedocs on the init pull request***

### CODE REVIEW

**Comment by RDIL** [comment]
Lmao it’s been more then a month with no activity...

**Comment by CoalCoding** [comment]
Does the owner of the repository have to go through these steps?

**Comment by RDIL** [comment]
Anybody that can authorize oAuth apps to the organization can @CoalCoding

**Comment by CoalCoding** [comment]
I believe an organisation owner will have to do this, @FalseHonesty

**Pull request closed without merging**
