### PR TITLE
UUIDS > Username

### PR DESCRIPTION
**Pull request by ChachyGit**

### CODE REVIEW

**Comment by Cubxity** [comment]
You can't compare UUID with String right

**Comment by ConorTheDev** [comment]
player.getUniqueID().toString().equals("");

**Comment by RDIL** [comment]
Oops

**Comment by Sk1er** [comment]
Yeah thats not a thing. https://sk1er.exposed/14.38.44-01.07.18.png
UUID will never equal a string. You could do UUID.fromString

**Pull request closed without merging**
