### PR TITLE
Finished Addon Installer Tab

### PR DESCRIPTION
**Pull request by ConorTheDev**

### CODE REVIEW

**Comment by ConorTheDev** [comment]
ok

**Comment by ConorTheDev** [comment]
I need to add 1 more thing to bypass 403 errors so I'll do that in that commit

**Comment by Cubxity** [comment]
Please use gson (JsonHolder)

**Comment by ConorTheDev** [comment]
Alright! :D

**Comment by ConorTheDev** [comment]
Give me a few minutes to port it.

**Pull request merged**
