### PR TITLE
Remove static things from keystrokes

### PR DESCRIPTION
**Pull request by boomboompower**

### CODE REVIEW

**Comment by boomboompower** [comment]
I honestly need to stop using a fork

**Comment by FalseHonesty** [comment]
you could do feature branches. (hi discord!)

**Comment by boomboompower** [comment]
Or I can actually get push access @FalseHonesty

**Comment by FalseHonesty** [comment]
tru

**Comment by MusicalCookie** [comment]
im joining in now

**Comment by FalseHonesty** [comment]
@Sk1er yehyehyeh

**Comment by ValsCSGO** [comment]
@FalseHonesty wow dude

**Comment by boomboompower** [comment]
FREEDOM

**Comment by MusicalCookie** [comment]
u should fix this

**Comment by ValsCSGO** [comment]
^ no

**Comment by MusicalCookie** [comment]
so lazy smh

**Pull request merged**
