### PR TITLE
Copyright headers

### PR DESCRIPTION
**Pull request by RDIL**

### CODE REVIEW

**Comment by asbyth** [comment]
is this all needed though? rarely ever see these being added

**Comment by RDIL** [comment]
people should know copyright is a thing
also sorry for email spam <3

**Comment by CoalCoding** [comment]
Use the IntelliJ copyright function in future and put it in one commit, also put this with the readme updates and grammar.

**Comment by RDIL** [comment]
What I’m going to try to do is make 1 PR with all these commits plus the
README plus the grammar

**Pull request closed without merging**
