### PR TITLE
customrp things

### PR DESCRIPTION
**Pull request by SHARDcoder**
ignore the 2nd and third commits
it did some stuff to files i didnt know were changed so i reverted it

### CODE REVIEW

**Comment by Cubxity** [comment]
whats this?

**Comment by ConorTheDev** [comment]
I'm confused, what is this? @SHARDcoder

**Comment by SHARDcoder** [comment]
i deleted the integrated version of customrp and edited the mod version to work with discordRP rather than 'combat' it for a connection to discord

**Comment by Cubxity** [comment]
- Why did you revert
- Why do we need custom presence tho

**Comment by SHARDcoder** [comment]
i reverted cos it changed stuff that i didnt know it had
idk its an integrated addon you can delete it if you want

**Comment by ConorTheDev** [comment]
^
I don't see a point for it *in my opinion*

**Comment by SHARDcoder** [comment]
ok

**Pull request closed without merging**
