### PR TITLE
spotify now shows the artist name

### PR DESCRIPTION
**Pull request by ConorTheOreo**
image

### CODE REVIEW

**Comment by DafsCode** [comment]
Odd one, but could you make it so that the artist name and song are always on separate lines, rather than having a - and a new line cause the song name is too long?

Like this:

Spotify
Now playing
Darude
Sandstorm

**Comment by ConorTheOreo** [comment]
#suggestions in the discord please!

**Comment by DafsCode** [comment]
I wouldn't really call it a suggestion, more a sort of "hey, that's cool, but it looks kinda won't" but alrighty

**Comment by DafsCode** [comment]
Wonky* lol

**Comment by FalseHonesty** [comment]
I am okay having people leave relevant comments in github issues or pull requests, so don't worry too much @DafsCode

**Pull request closed without merging**
