### PR TITLE
big head texture (for players)

### PR DESCRIPTION
**Pull request by emanh1**
not for other entities heads

### CODE REVIEW

**Comment by emanh1** [comment]
just make the head big when its dropped lul

**Comment by FalseHonesty** [comment]
Big heads work currently though i thought?

**Comment by emanh1** [comment]
but it isn't meant to be big in inventory

**Comment by FalseHonesty** [comment]
Yes, which was fixed in a previous update

**Comment by emanh1** [comment]
ah k didn't see that

**Pull request closed without merging**
