### PR TITLE
Slight cleanup

### PR DESCRIPTION
**Pull request by DeJayDev**
Slight Cleanup of my earlier PR.

### CODE REVIEW

**Comment by asbyth** [comment]
thing is, it's not used anywhere, nowhere does it call this method

also you forgot the imports and the field for okClient

**Comment by DeJayDev** [comment]
This conflict is going to kill me.

**Comment by asbyth** [comment]
still an unused method, and exclude okhttp from MojangAPI if you're going to be updating it

**Comment by asbyth** [comment]
ever plan on finishing? @DeJayDev

**Pull request closed without merging**
