### PR TITLE
i want fuit gummy

### PR DESCRIPTION
**Pull request by AmpTheDev**
i want fuit gummy

### CODE REVIEW

**Comment by grummycodez** [comment]
its i want fruit grummy not gummy dumbo

**Comment by GamingGeek** [comment]
@grummycodez shut up don't add useless comments thank

**Comment by grummycodez** [comment]
@GamingGeek yes papa

**Comment by AmpTheDev** [comment]
that's just your ego @grummycodez it's actually fuit gummy, my source is https://oh-my-god.wtf

**Comment by grummycodez** [comment]
isn't that like one of geeks fake news sites

**Comment by GamingGeek** [comment]
shut. the. frick. up. don't comment unless it's actually meaningful and related to the pr

**Comment by grummycodez** [comment]
YES OK

**Pull request merged**
