### PR TITLE
Let the server know what addons player is using

### PR DESCRIPTION
**Pull request by libhalt**
Servers should be able to tell what addon player is using. As hyperium has the abillity for any user to create addons that can load on the platform, server may want to block certain addon from being used. While this does not prevent users who have mallicous intent, this does allow server's to block certain addons for players who do not have mallicious intent and just simply loaded random addon that they downloaded on the internet. Our aim is to let the innocent player know that the addon they are using is not allowed on the server, and they should remove it if they want to play.

While caching the JsonObject may result in much cleaner code, I aimed the code to be minimal diff as possible. Even if this does not get merged, I request same feature to be added to this mod.

### CODE REVIEW

**Comment by Sk1er** [comment]
This is ineffective. They could just mixin our code to stop it from sending or mix the packet manager and cancel it there

**Comment by libhalt** [comment]
As I stated this isnt for players who have mallicious intent but for innocent people who downloaded something they dont know isnt allowed

**Comment by ConorTheDev** [comment]
I don’t see the point in this as Sk1er said, it’s easy to bypass.

**Comment by ConorTheDev** [comment]
People can make their addons bypass this, then it’s just ineffective

**Comment by CoalCoding** [comment]
Also if something isn't allowed we wouldn't put it up to be downloaded, so innocent players would be very unlikely to accidentally download a disallowed addon.

**Comment by ConorTheDev** [comment]
^

**Comment by libhalt** [comment]
Well the usecase that I wanted to aim is that somebody decided to port particle mod / npc mod to hyperium and both of these mod's triggers our anticheats. Now because the guy whoever did this decide to distribute his broken addon on his discord, people are getting banned. On forge, we block these mods, but on hyperium theres no way to tell, If they decided to bypass the system thats letting us know then fuck them and they'll stay banned lol

**Comment by ConorTheDev** [comment]
Yeah, but that’s his issue for making people get banned with the addon, I remember a case where 2PI ported a mod to 1.8.9 and it got people banned, did they blame Forge? No.

**Comment by Sk1er** [comment]
Switch it to be in MixinNetHandlerPlayClient#handleCustomPayload as that is the appropriate place to send a response about the client

**Comment by libhalt** [comment]
Initially, it was in there, but I had to decide the following which was hard decision for me so I put it in the xisiting payload.

1. The name of the channel. is hyperium|Addons really suitable?
2. Should we write json or should we prepend the buffer with mod size integer and write string (mod name) , and string(version) into the packetbuffer in loop just like how forge is?

for 2, I decided to use json for now because its future-proof (In case if we every want to send more data about mod although thats unlikely)

If you have a good decesion for 1 and 2 , please feel free to commend and I will be more than happy to adjust

**Comment by libhalt** [comment]
NPC Mod litterally spams HeldItemChange with the newslot == oldslot

**Pull request merged**
