### PR TITLE
added dependencies for addons.

### PR DESCRIPTION
**Pull request by 9Y0**
wow I wrote kotlin. I feel special now

### CODE REVIEW

**Comment by 9Y0** [comment]
some more stuff needs to be added. closed for now

**Comment by FalseHonesty** [comment]
You could just mark this as WIP rather than closing.

**Comment by 9Y0** [comment]
I cant do it I think(or I'm dumb) but would be nice if you or someone else could add it

**Comment by FalseHonesty** [comment]
I mean you could just put "WIP" in the title or something, but I'll make a label if you'd like.

**Comment by 9Y0** [comment]
- added topological sort for addon loading
- an gui will show up when starting the game when there's something wrong with addon loading

can be merged

**Pull request merged**
